image:
  repository: mariadb 
  tag: 10.5
  pullPolicy: IfNotPresent

service:
  type: NodePort 
  port: 3306

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteMany
  size: 10Gi

mysql:
  rootPassword: "password"
