apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: {{ .Release.Name }}-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: MARIADB_ROOT_PASSWORD 
            value: {{ .Values.mysql.rootPassword }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
