apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-db-app.fullname" . }}
  labels:
    {{- include "my-db-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-db
